### ISSUE TITLE
Speed percent changes by itself. 

### ISSUE THREAD

**Issue by polacoloco** [bigtreetech/BTT-TFT35-E3-V3.0#57] opened 2021-01-05 22:57 UTC
Often I have to select the speed percent and change it back to normal (100%).  Something is randomly putting in other percentages like 104%, 242%, 123% and so on. I have to be really careful to check this and not starting a print with the speed set to high. Really annoying!

**Comment by oldman4U** [comment] 2021-01-07 13:47
Do you see two values when you change a setting like speed, flow or fan?

**Comment by DerInternets** [comment] 2021-01-07 21:37
Same issue here - menu shows xxx/xxx - so current / expected value. I also get completely random speed settings from time to time. Last value was nearly 400% - the noises my double z-axis motors made when trying to move 50mm upwards were horrible.

**Comment by oldman4U** [comment] 2021-01-08 11:03
Maybe a video showing the issue would help.

**Comment by sarvenn** [comment] 2021-01-09 09:04
I had the same issue whenever I change the speed manually. Even while changing the percentage value to %100 manually it jump again to a different value.

**Comment by oldman4U** [comment] 2021-01-09 10:06
Load the master firmware and let us know.

**Comment by oldman4U** [comment] 2021-01-09 22:22
Any news?

**Comment by polacoloco** [comment] 2021-01-10 12:47
Im no expert on this stuff. Where can i find the master firmware? Ive just downloaded the files from this page.

**Comment by radek8** [comment] 2021-01-10 19:38
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update

**Comment by polacoloco** [comment] 2021-01-10 22:32
> https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update

This is the files that are currently in my tft. I had the same issue with the stock firmware on the tft.

**Comment by oldman4U** [comment] 2021-01-10 22:33
Please make a movie which shows the issue and attach it here.

**Comment by radek8** [comment] 2021-01-10 23:09
The speed changes when you turn the encoder wheel ....
Am I right? :-)

**Comment by radek8** [comment] 2021-01-10 23:21
This is a well-known problem.
If you only use EXP3 to connect Marlin and TFT, you have this problem.
This could also be addressed, but Marlin will need to be modified and another wire connected. I haven't tried it, but it should work.

**Comment by oldman4U** [comment] 2021-01-11 11:38
By itself is something different for me....😁

**Comment by oldman4U** [comment] 2021-01-12 21:36
Any news?

Please let us know or close the ticket.

Thank you

**Comment by polacoloco** [comment] 2021-01-13 09:53
> This is a well-known problem.
> If you only use EXP3 to connect Marlin and TFT, you have this problem.
> This could also be addressed, but Marlin will need to be modified and another wire connected. I haven't tried it, but it should work.

I use two cables to connect the tft to my skr mini e3 v2.0. The ones that came with the tft. How should I modify marlin?

**Comment by oldman4U** [comment] 2021-01-13 10:08
Please upload a movie showing the issue.

**Comment by radek8** [comment] 2021-01-13 12:56
Yes, you are using 2 cables.
1pc - 10pin for Marlin mode
1pc - 5pin for touch mode.
you have a SKR mini V2.0 board - important information!
What version does your display have?
Can you confirm that the problem is with changing the print speed if you turn the encoder knob?

**Comment by polacoloco** [comment] 2021-01-13 15:14
Yes

**Comment by polacoloco** [comment] 2021-01-13 15:19
Yes, now I noticed. F.ex when I increase the nozzle temperature with the knob, when I go back to the main screen the print speed has changed. 

Tried to upload a video but was over 10MB so it didn’t upload.

**Comment by radek8** [comment] 2021-01-13 17:13
No video required. Oldman4U finds some other erotic video on Youtube :-)

**Comment by radek8** [comment] 2021-01-13 17:22
Now write me what type of display you have.
The problem described is a HW problem in the encoder connection.
This problem can be solved by SW repair.
Write me what version of Marlin you are using (must be newer than 25.10.2020)
I also need to know which pin you don't use on the marlin board and maybe use it.

**Comment by polacoloco** [comment] 2021-01-13 21:54
#
![FC032411-4CA5-4929-963F-3CE7330DB366](https://user-images.githubusercontent.com/77029233/104514817-2bc96e80-55f2-11eb-9328-a73f50c35235.jpeg)

pins not being used I don’t know. Got no extra fans or stuff like that connected. Only the bltouch.

**Comment by radek8** [comment] 2021-01-13 23:25
Try this adjustment:
1. connect pin PC13 on SKR to pin PC6 on TFT.

![image](https://user-images.githubusercontent.com/46979052/104522179-9a142e00-55fe-11eb-8c41-7a7bf008c125.png)

2. Edit the file "pins_BTT_SKR_MINI_E3_V2_0.h" according to the picture

![image](https://user-images.githubusercontent.com/46979052/104523045-d21b7100-55fe-11eb-9286-22ae6a0ca9cc.png)

#if ENABLED(CR10_STOCKDISPLAY)
   #define BTN_ENC_EN        PC13  // Detect the presence of the encoder
#endif

3. Compile and upload the new Marlin.

**Comment by polacoloco** [comment] 2021-01-14 07:16
Thanks! I will try this as soon as possible and get back to you with the results!

**Comment by radek8** [comment] 2021-01-14 18:25
@polacoloco, beware your version of Marlin does not have a patch implemented. 
Use Marlin "Nightly" Builds = bugfix-2.0.x

https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

**Comment by demandzm** [comment] 2021-01-15 03:28
I have the same issue with a tft35 v3 connected to a skr1.4 turbo with ext1 ext2 and serial. Does this fix still apply with 3 cables?

**Comment by radek8** [comment] 2021-01-15 06:30
The correction was implemented in the 10th month of 2020.
It uses a free pin on the EXP1 connector to detect the mode
Therefore, if you have the current FW on the TFT and the EXP1 + EXP2 + RS232 connector is used for the connection, you should not have this problem.
If you have this problem, it means that you do not have an up-to-date Marlin.
Use Marlin "Nightly" Builds = bugfix-2.0.x
https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x
The stable version 2.0.7.2 does not yet contain the fix.

**Comment by oldman4U** [comment] 2021-01-17 22:29
Any news?

**Comment by oldman4U** [comment] 2021-01-20 18:23
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by polacoloco** [comment] 2021-01-20 19:56
> Please help the community and close the ticket once you do not need it anymore. Thank you

I will. I promise. Don’t you worry bout that. My printer is currently being rebuilt so it might take a couple of days. 
Thank you

**Comment by oldman4U** [comment] 2021-01-20 21:41
Perfect

Happy printing

polacoloco <notifications@github.com> schrieb am Mi. 20. Jän. 2021 um 20:56:

**Comment by craftyham** [comment] 2021-02-06 16:33
> 
> 
> Often I have to select the speed percent and change it back to normal (100%). Something is randomly putting in other percentages like 104%, 242%, 123% and so on. I have to be really careful to check this and not starting a print with the speed set to high. Really annoying!

I noticed this as well. I have yet to pin point when it happens; & what was done last.

**Comment by oldman4U** [comment] 2021-02-06 16:43
In case you see only one value and not two (current/defined) you have an
old firmware of the TFT.

Update and you will see two values and the problem will be gone.

craftyham <notifications@github.com> schrieb am Sa. 6. Feb. 2021 um 17:34:

**Comment by polacoloco** [comment] 2021-02-06 20:46
> > Often I have to select the speed percent and change it back to normal (100%). Something is randomly putting in other percentages like 104%, 242%, 123% and so on. I have to be really careful to check this and not starting a print with the speed set to high. Really annoying!
> 
> I noticed this as well. I have yet to pin point when it happens; & what was done last.

It’s when you use the encoder knob to change other values such as nozzle temp, it actually change the speed percent in the background. Stop using the knob and the speed will stop changing. Try it

**Comment by oldman4U** [comment] 2021-02-06 20:55
Correct. Using latest version this has been fixed for mainboards connected
via EXP 1and 2 but can not be fixed in case of EXP 3 connected mainboards.

polacoloco <notifications@github.com> schrieb am Sa. 6. Feb. 2021 um 21:46:

**Comment by radek8** [comment] 2021-02-07 13:38
@polacoloco have you tried my proposed edit?

**Comment by oldman4U** [comment] 2021-02-15 13:15
Please help the community and close the ticket once you do not need it anymore. Thank you

**Closed as completed** 2021-02-15 20:11 UTC

**Comment by phongshader** [comment] 2021-09-17 21:30
I realize this has been closed for a while but I having this exact issue. I'm running Marlin bugfix-2.0x 09/11/21 and BIGTREE_TFT35_V3.0_E3.27.x.bin from the same day.
when I start the printer the speed is 100% when I load gcode the speed multiplier jumps to anything from 150% to 350%. I can reset the multiplier to 100% but if I load the same gcode the multiplier will change to some other greater speed multiplier. The multiplier is NOT in the gcode.
Is there a fix for this, other than not using the knob to adjust settings?

**Comment by oldman4U** [comment] 2021-09-18 05:58
You can fix it by buying a mainboard which connects via EXP1 and 2 or disable Marlin on yours.

**Comment by radek8** [comment] 2021-09-18 08:21
@phongshader .
You didn't specify what Marlin board you were using.
This is quite important information.

It is a well-known problem that has several solutions.
1. You stop using the encoder in touch mode
2. disconnect the EXP3 cable and you will not be using Marlin mode
3. you buy a board that has EXP1 and EXP2 connectors
4. In Marlin, disable the return to the status screen after the set time has elapsed and after turning on the printer, just one click on the encoder and then you can rotate the encoder and the speed will not change. Be careful not to click in touch mode anymore.
5. Use the hack above. https://github.com/bigtreetech/BTT-TFT35-E3-V3.0/issues/57#issuecomment-759822436

I recommend the 4th solution. I used it myself before it was repaired when using cable EXP1 and 2
Just set in Configuration_adv.h
#define LCD_TIMEOUT_TO_STATUS -1

The speed changes when the encoder is rotated while the Marlin status screen is on the screen (even when the display is switched to touch). If you exit the status screen by clicking once and prevent the status screen from automatically returning after the set time has elapsed, the speed will no longer change.

**Comment by phongshader** [comment] 2021-09-19 14:39
Sorry, the board is a skr mini e3 v2 running Marlin bugfix-2.0x 09/11/21. So there is no solution that keeps the full functionality of the touchscreen/marlin mode? When you say the hack above are you referring to https://github.com/bigtreetech/BTT-TFT35-E3-V3.0/issues/57#issuecomment-759822436

**Comment by radek8** [comment] 2021-09-19 14:46
Yes. 
There are five solutions. I've described them all. 
3. 4. and 5. will maintain the full functionality of both interfaces

**Comment by phongshader** [comment] 2021-09-19 17:08
Thank you...solutions...sort of, 3 is not really a solution, change the horse to fit the shoe?, 4 "Be careful not to click in touch mode anymore." 5 is really the only solution, unless I'm misunderstanding how 4 works. Nevertheless I can work around this with a startup script in the slicer.

**Comment by radek8** [comment] 2021-09-19 18:02
Never click the encoder in touch mode!
You can only spin the encoder if you can get the pulses of the coder to keep the Marlins from.

**Comment by radek8** [comment] 2021-09-19 18:54
How would you like to handle this in the startup script?

**Comment by phongshader** [comment] 2021-09-19 19:22
simple,  m220 s100 so it gets reset to 100 regardless of what the encoder says...right?

**Comment by radek8** [comment] 2021-09-19 20:32
Yes, when you start printing you will have a speed of 100%, but you will find that you need to tune the child step or temperature. As soon as you touch the encoder, you also change the print speed.
This is not a good solution.

**Comment by radek8** [comment] 2021-09-19 20:34
The M220 S100 command only sets the value.
It does not block input from the encoder

**Comment by oldman4U** [comment] 2021-09-19 21:16
If this would work it would only make sense if you would be able to change the print speed using the encoder before you started the print. Or is it that I have too many twists in my brain because of the strange thinking!!??

Marlin mode - use encoder
Touchscreen mode - use the touchscreen
