### ISSUE TITLE
Display not functional

### ISSUE THREAD

**Issue by petenut** [bigtreetech/BTT-TFT35-E3-V3.0#30] opened 2020-08-23 17:17 UTC
Hello, I am upgrading my display from V2.0 to V3.0. The V3.0 display LED backlights turn on, but the display does not show any image and does not seem functional. Please help.

**Comment by oldman4U** [comment] 2020-08-23 19:55
Which mainboard?
Pictures of the cables?
Firmware version?
What else is attached to mainboard and TFT?

**Comment by petenut** [comment] 2020-08-24 02:08
Hello,
   Sorry for not including the details.

AnyCubic Kossel Linear

BTT SKR 1.3 main board
 - heated bed
 - hot end
 - driver cooling fan
 - Marlin 2.0

No other peripherals connected.

I have tried only using the serial cable, only the EXP cables and a combination of both sets of cables.

The backlight turns on,  but the display doesn’t function.

Your help is much appreciated.

Thank you,



J Petrie
Sent from my iPhone

On Aug 23, 2020, at 1:55 PM, oldman4U <notifications@github.com> wrote:

﻿

Which mainboard?
Pictures of the cables?
Firmware version?
What else is attached to mainboard and TFT?

**Comment by oldman4U** [comment] 2020-08-24 05:03
Looks like a hardware issue to me. Have you tried to upload a new firmware?

petenut <notifications@github.com> schrieb am Mo. 24. Aug. 2020 um 04:08:

>
>
>
> Hello,
>
>
>
>
>
>
> Sorry for not including the details.
>
>
>
>
>
>
>
>
>
>
>
>
>
> AnyCubic Kossel Linear
>
>
>
>
>
>
>
>
>
>
>
>
>
> BTT SKR 1.3 main board
>
>
>
>
>
>
> - heated bed
>
>
>
>
>
>
> - hot end
>
>
>
>
>
>
> - driver cooling fan
>
>
>
>
>
>
> - Marlin 2.0
>
>
>
>
>
>
>
>
>
>
>
>
>
> No other peripherals connected.
>
>
>
>
>
>
>
>
>
>
>
>
>
> I have tried only using the serial cable, only the EXP cables and a
> combination of both sets of cables.
>
>
>
>
>
>
>
>
>
>
>
>
>
> The backlight turns on, but the display doesn’t function.
>
>
>
>
>
>
>
>
>
>
>
>
>
> Your help is much appreciated.
>
>
>
>
>
>
>
>
>
>
>
>
>
> Thank you,
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> J Petrie
>
>
>
>
>
>
> Sent from my iPhone
>
>
>
>
>
>
>
>
>
>
>
>
>

**Comment by petenut** [comment] 2020-08-25 13:40
Hello,
   I just tried to flash the firmware but same result. Backlight is on but the screen is black. Can I exchange this unit?

Thank you,


J Petrie
Sent from my iPhone

On Aug 23, 2020, at 11:04 PM, oldman4U <notifications@github.com> wrote:

﻿

Looks like a hardware issue to me. Have you tried to upload a new firmware?

petenut <notifications@github.com> schrieb am Mo. 24. Aug. 2020 um 04:08:

>
>
>
> Hello,
>
>
>
>
>
>
> Sorry for not including the details.
>
>
>
>
>
>
>
>
>
>
>
>
>
> AnyCubic Kossel Linear
>
>
>
>
>
>
>
>
>
>
>
>
>
> BTT SKR 1.3 main board
>
>
>
>
>
>
> - heated bed
>
>
>
>
>
>
> - hot end
>
>
>
>
>
>
> - driver cooling fan
>
>
>
>
>
>
> - Marlin 2.0
>
>
>
>
>
>
>
>
>
>
>
>
>
> No other peripherals connected.
>
>
>
>
>
>
>
>
>
>
>
>
>
> I have tried only using the serial cable, only the EXP cables and a
> combination of both sets of cables.
>
>
>
>
>
>
>
>
>
>
>
>
>
> The backlight turns on, but the display doesn’t function.
>
>
>
>
>
>
>
>
>
>
>
>
>
> Your help is much appreciated.
>
>
>
>
>
>
>
>
>
>
>
>
>
> Thank you,
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> J Petrie
>
>
>
>
>
>
> Sent from my iPhone
>
>
>
>
>
>
>
>
>
>
>
>
>

**Comment by oldman4U** [comment] 2020-08-25 17:00
Can you see the firmware flashing?

Contact your dealer for exchange.

petenut <notifications@github.com> schrieb am Di. 25. Aug. 2020 um 15:41:

>
>
>
> Hello,
>
>
>
>
>
>
> I just tried to flash the firmware but same result. Backlight is on but
> the screen is black. Can I exchange this unit?
>
>
>
>
>
>
>
>
>
>
>
>
>
> Thank you,
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> J Petrie
>
>
>
>
>
>
> Sent from my iPhone
>
>
>
>
>
>
>
>
>
>
>
>
>

**Comment by oldman4U** [comment] 2020-08-27 08:05
Any news?

**Comment by petenut** [comment] 2020-08-27 11:37
Hello, I have returned the original display item and have received a new one. I haven’t had a chance to test the new display.

J Petrie
Sent from my iPhone

On Aug 27, 2020, at 2:05 AM, oldman4U <notifications@github.com> wrote:

﻿

Any news?

**Comment by oldman4U** [comment] 2020-08-28 05:19
Let me know if it is fixed.

**Comment by petenut** [comment] 2020-08-29 16:56
Hello,
    I have received the replacement display and I’m able to get the graphics menus to work. When I push the encoder knob I get the option to switch to Marlin but the screen goes black when I select it. I’m able to hold the knob down and go back tot the graphical menus but I’m not happy because I bought this display specifically to access the Marlin options. I’ve read one of the guides on Github but I don’t know what the solution is to fix this problem.

Please advise.

Thank you,



J Petrie
Sent from my iPhone

On Aug 27, 2020, at 11:19 PM, oldman4U <notifications@github.com> wrote:

﻿

Let me know if it is fixed.

**Comment by oldman4U** [comment] 2020-08-30 07:29
Have you tried to rotate the knob once you entered Marlin mode? This is needed to switch from black to screen. Let me know.

**Comment by petenut** [comment] 2020-08-30 12:40
Hello, yes I tried to rotate the knob and press the knob after changing modes but the Marlin menus still don’t appear. What should I try next?

Thank you,



J Petrie
Sent from my iPhone

On Aug 30, 2020, at 1:30 AM, oldman4U <notifications@github.com> wrote:

﻿

Have you tried to rotate the knob once you entered Marlin mode? This is needed to switch from black to screen. Let me know.

**Comment by oldman4U** [comment] 2020-08-30 16:35
How have you connected the TFT with the mainboard?

**Comment by petenut** [comment] 2020-08-30 17:01
Yes sir. I have all three cables (Exp 1, Exp 2 and TFT) connected to the main board.

J Petrie
Sent from my iPhone

On Aug 30, 2020, at 10:35 AM, oldman4U <notifications@github.com> wrote:

﻿

How have you connected the TFT with the mainboard?

**Comment by oldman4U** [comment] 2020-09-03 12:53
Sorry for the late answer.

Do you compile firmware by yourself or do you use precompiled firmware?

**Comment by petenut** [comment] 2020-09-04 13:00
I’ve actually been having a hard time getting the firmware to compile so I’m stuck at the moment.

What software do you recommend? I have VS code/PIO.

Thank you,



J Petrie
Sent from my iPhone

On Sep 3, 2020, at 6:54 AM, oldman4U <notifications@github.com> wrote:

﻿

Sorry for the late answer.

Do you compile firmware by yourself or do you use precompiled firmware?

**Comment by oldman4U** [comment] 2020-09-04 13:55
I use the same on Mac.  What is the problem with the comp. ?

petenut <notifications@github.com> schrieb am Fr. 4. Sep. 2020 um 15:00:

>
>
>
> I’ve actually been having a hard time getting the firmware to compile so
> I’m stuck at the moment.
>
>
>
>
>
>
>
>
>
>
>
>
>
> What software do you recommend? I have VS code/PIO.
>
>
>
>
>
>
>
>
>
>
>
>
>
> Thank you,
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> J Petrie
>
>
>
>
>
>
> Sent from my iPhone
>
>
>
>
>
>
>
>
>
>
>
>
>

**Comment by oldman4U** [comment] 2020-09-07 15:59
Any news?

**Comment by oldman4U** [comment] 2020-09-07 19:29
When you have a problem with compiling, try to delete the platforms and packages folder. On the Mac this can be found under: /Users/username/.platformio/ - which is a hidden folder.

Start VSC after that.

**Comment by petenut** [comment] 2020-09-08 16:08
Hello,
    I have been able to upload a new firmware (previously compiled .bin) and now I get the LCD12864 SILUMATOR message when I switch to Marlin, but I do not get the other options, even after moving the encoder. What should I try next?

Thank you,



J Petrie
Sent from my iPhone

On Sep 7, 2020, at 1:29 PM, oldman4U <notifications@github.com> wrote:

﻿

When you have a problem with compiling, try to delete the platforms and packages folder. On the Mac this can be found under: /Users/username/.platformio/ - which is a hidden folder.

Start VSC after that.

**Comment by oldman4U** [comment] 2020-09-08 16:17
PROGRESS. Yeah👍🏻😁

So touchscreen works?

Cables?
Which kind of display is defined in Configuration.h of the mainboard?

**Comment by petenut** [comment] 2020-09-08 16:46
Yes, touchscreen works, but Marlin controls do not show up.

From SKR1.3 board firmware

Port settings:
Serial_port 1
Serial_port_2 0

Display settings:

Rep rap_discount_full_graphic_smart_controller

J Petrie
Sent from my iPhone

On Sep 8, 2020, at 10:17 AM, oldman4U <notifications@github.com> wrote:

﻿

PROGRESS. Yeah👍🏻😁

So touchscreen works?

Cables?
Which kind of display is defined in Configuration.h of the mainboard?

**Comment by oldman4U** [comment] 2020-09-08 17:15
Port settings are fine, because the touchscreen works.
Cables are fine, because otherwise you would not get the message.
You tried to rotate the knob, once the LCD12864 SIMULATOR shows up?

Please check in Marlin of your mainboard if the CR10 display is also activated and make sure it is not activated.

Let me know

**Comment by petenut** [comment] 2020-09-08 17:46
Hello,
   I just changed the settings to:

Serial 1 -1
Serial 2 0

After reflashing the firmware, the Greenscreen is working!

Thank you for your help.

J Petrie
Sent from my iPhone

On Sep 8, 2020, at 11:16 AM, oldman4U <notifications@github.com> wrote:

﻿

Port settings are fine, because the touchscreen works.
Cables are fine, because otherwise you would not get the message.
You tried to rotate the knob, once the LCD12864 SIMULATOR shows up?

Please check in Marlin of your mainboard if the CR10 display is also activated and make sure it is not activated.

Let me know

**Comment by oldman4U** [comment] 2020-09-08 18:26
Greenscreen?

You make me nervous...😳

**Comment by oldman4U** [comment] 2020-09-16 05:25
Please respond or close this ticket in case the problem is solved. Thank you

**Comment by petenut** [comment] 2020-09-16 12:09
Hello Sir, yes the issue has been resolved. You may close the ticket.

Thank you,



J Petrie
Sent from my iPhone

On Sep 15, 2020, at 11:25 PM, oldman4U <notifications@github.com> wrote:

﻿

Please respond or close this ticket in case the problem is solved. Thank you

**Comment by oldman4U** [comment] 2020-09-16 19:02
Petenut.

Only you can close this ticket by clicking on the Close button at the bottom of this ticket.

Please do so

Thank you

**Closed as completed** 2020-09-16 20:32 UTC

**Comment by oldman4U** [comment] 2020-09-16 20:34
Thank you and happy printing

👍🏻

petenut <notifications@github.com> schrieb am Mi. 16. Sep. 2020 um 22:32:
