### ISSUE TITLE
Babystepping not available in TFT mode

### ISSUE THREAD

**Issue by JoeK1973** [bigtreetech/BTT-TFT35-E3-V3.0#16] opened 2020-05-09 14:45 UTC
I am on the latest firmware on both TFT35 E3 v3 (3.26.1) and Marlin 2.0.5.3 on SKR Mini E3 v1.2

I have babystepping available on Marlin mode but not in TFT35 mode.

**Comment by oldman4U** [comment] 2020-07-03 19:09
Hi.

Could you please test with the latest "Master" firmware of the TFT. I can execute Babystepping while printing and change it from TFT during a print.

**Comment by oldman4U** [comment] 2020-07-11 16:49
Hi. 

Could you please reply or close this ticket in case the issue is solved in the meantime. 

Thank you

**Comment by JoeK1973** [comment] 2020-07-11 18:12
Hi,

Yes that fixed it.

Thanks

**Comment by oldman4U** [comment] 2020-07-11 18:13
👍Great. Please close the ticket 

Thank you

**Comment by oldman4U** [comment] 2020-07-18 21:22
@bigtreetech This issue is solved but the user is not able to close it for an unknown reason. Could you please close it. 

Thank you

**Comment by oldman4U** [comment] 2020-08-05 09:21
With the latest release it is also possible to save the babysteps. 

Please close this ticket

**Comment by oldman4U** [comment] 2020-09-23 14:34
Please help the community and close the ticket once you do not need it anymore. Thank you

**Closed as completed** 2020-09-23 14:42 UTC
